---
title: "CV Analysis of mpg data"
author: "Ian Handel"
date: "2019-02-05"
output: github_document
---


```{r}
library(tidyverse)
library(here)
library(rsample)
library(yardstick)
library(broom)
library(gt)
```

### Load clean data

```{r}
dat <- read_csv(here("data", "clean", "mpg_data_clean.csv"))
```

### Resample

```{r}
cv <- dat %>%
  rsample::vfold_cv(v = 10)

print(cv)
```

### Fit lm of hwy mpg on displacement and cylinder number

```{r}
cv <- cv %>%
  mutate(model = map(splits, ~ lm(hwy ~ factor(cyl) + displ,
    data = as_tibble(.x)
  ))) %>%
  mutate(fit = map(model, tidy))

print(cv)
```

### predict on withheld data

```{r}
cv <- cv %>%
  mutate(predict = map2(
    splits,
    model, ~ tibble(
      predict = predict(.y, as_tibble(.x)[-.x$in_id, ]),
      actual = as_tibble(.x)[-.x$in_id, ]$hwy
    )
  ))

print(cv)
```

### Add rmse

```{r}
cv <- cv %>%
  mutate(rmse = map(predict, ~ rmse(.x, actual, predict))) %>%
  unnest(rmse)
```

### Plot fits

```{r}
cv %>%
  unnest(fit) %>%
  ggplot() +
  aes(x = id, y = estimate) +
  geom_point() +
  facet_wrap(~term, scale = "free") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))

ggsave(here("output", "figure_1.pdf"), height = 6, width = 5)
```

### Report RMSE

```{r}
cv %>%
  summarise(
    mean_rmse = mean(.estimate),
    min_rmse = min(.estimate),
    max_rmse = max(.estimate)
  )
```


